ccflags-y += -I$(srctree)/drivers/misc/mediatek/m4u/mt6735
ccflags-y += -I$(srctree)/drivers/misc/mediatek/mmp/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/m4u/2.0
ccflags-y += -I$(srctree)/drivers/misc/mediatek/m4u/$(MTK_PLATFORM)/mt6735m/
obj-y += m4u_platform.o
